"""encrypt_billing_period_dates

Revision ID: 6a44d4731b68
Revises: 767293a7a062
Create Date: 2026-06-14 16:12:23.585108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6a44d4731b68'
down_revision: Union[str, Sequence[str], None] = '767293a7a062'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('billing_payments', 'period_start',
               existing_type=mysql.DATETIME(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('billing_payments', 'period_end',
               existing_type=mysql.DATETIME(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('billing_payments', 'period_end',
               existing_type=sa.Text(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
    op.alter_column('billing_payments', 'period_start',
               existing_type=sa.Text(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
    # ### end Alembic commands ###
