"""add_proformas_invoices_image_url_returns_appconfig

Revision ID: 97b2563a8560
Revises: 4dc5c4ca1d2e
Create Date: 2026-06-11 12:22:38.564447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '97b2563a8560'
down_revision: Union[str, Sequence[str], None] = '4dc5c4ca1d2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('method', sa.String(length=20), nullable=True))
    op.add_column('payments', sa.Column('note', sa.Text(), nullable=True))
    op.drop_column('payments', 'payment_methode')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('payment_methode', mysql.ENUM('CASH', 'BANK', 'MOBILE'), nullable=True))
    op.drop_column('payments', 'note')
    op.drop_column('payments', 'method')
    # ### end Alembic commands ###
