"""add_subscription_ends_at_to_tenant

Revision ID: 9e632a4b6a64
Revises: 24f7d83b5055
Create Date: 2026-07-15 12:29:08.351772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e632a4b6a64'
down_revision: Union[str, Sequence[str], None] = '24f7d83b5055'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.add_column('tenants', sa.Column('subscription_ends_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'subscription_ends_at')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    # ### end Alembic commands ###
