"""add_months_to_billing_payment

Revision ID: ca853a4cc1f8
Revises: 9e632a4b6a64
Create Date: 2026-07-15 12:46:44.695819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca853a4cc1f8'
down_revision: Union[str, Sequence[str], None] = '9e632a4b6a64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing_payments', sa.Column('months', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('billing_payments', 'months')
    # ### end Alembic commands ###
