from pydantic import BaseModel, EmailStr
from typing import Optional
from datetime import datetime


class TenantRegister(BaseModel):
    business_name: str
    owner_email: EmailStr
    password: str
    phone: Optional[str] = None


class TenantRead(BaseModel):
    id: str
    slug: str
    business_name: str
    owner_email: str
    status: str
    trial_ends_at: Optional[datetime] = None
    created_at: datetime

    class Config:
        from_attributes = True


class CloudLogin(BaseModel):
    email: EmailStr
    password: str
    device_id: Optional[str] = None   # UUID generated by the Flutter app
    register_name: Optional[str] = None  # "Caisse 1" — used on first login of a new device


class CloudToken(BaseModel):
    access_token: str
    token_type: str = "bearer"
    tenant: TenantRead
    user: dict
    register_id: Optional[str] = None
