from sqlalchemy import Column, String, Boolean, ForeignKey, UniqueConstraint
from .base import UUIDBase


class PosRegister(UUIDBase):
    __tablename__ = "pos_registers"

    tenant_id  = Column(String(36), ForeignKey('tenants.id'), nullable=False, index=True)
    name       = Column(String(100), nullable=False)   # "Caisse 1", "Caisse 2"…
    device_id  = Column(String(36),  nullable=False)   # UUID generated by the app
    is_active  = Column(Boolean, nullable=False, default=True)

    __table_args__ = (
        UniqueConstraint('tenant_id', 'device_id', name='uq_register_tenant_device'),
    )
